[package]
name = "dumb-auth"
version = "0.1.0"
authors = ["Dana Sommerich"]
edition = "2021"
description = "A stupid-simple, super-lightweight, single-user auth server."
repository = "https://github.com/sommd/dumb-auth"
license = "AGPL-3.0-only"

[dependencies]
axum = { version = "0.7.9", default-features = false, features = ["http1", "json", "tokio"] }
axum-extra = { version = "0.9.6", default-features = false, features = ["cookie", "typed-header"] }
clap = { version = "4.5.23", features = ["derive", "env"] }
constant_time_eq = "0.3.1"
duration-str = { version = "0.12.0", default-features = false, features = ["serde", "time"] }
form_urlencoded = "1.2.1"
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
time = "0.3.37"
tokio = { version = "1.42.0", features = ["rt", "macros"] }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[dev-dependencies]
reqwest = { version = "0.12.11", default-features = false, features = ["cookies", "json"] }
tokio-util = { version = "0.7.13", features = ["rt"] }
