name: Docker
description: Build and push dumb-auth Docker image
inputs:
  image:
    description: The image to build
    required: true
  platforms:
    description: The platforms to build for
    default: linux/amd64,linux/arm64
  tag:
    description: Tag for the image
    required: true
  latest:
    description: Also tag as latest
    default: "false"
runs:
  using: composite
  steps:
    - name: Setup QEMU
      if: inputs.platforms != 'linux/amd64'
      uses: docker/setup-qemu-action@v3
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        pattern: dumb-auth-*-linux-*
        path: binaries
        merge-multiple: true
    - name: Rename binaries
      shell: bash
      run: |
        cd binaries

        for f in dumb-auth-*; do
          target="${f#dumb-auth-}"
          arch="${target%%-*}"
          libc="${target##*-}"

          # Map to Docker arch
          if [[ "$arch" == x86_64 ]]; then arch=amd64; fi
          if [[ "$arch" == aarch64 ]]; then arch=arm64; fi

          mv "$f" "dumb-auth-$arch-$libc"
        done
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: docker/${{ inputs.image }}
        build-contexts: binaries=binaries
        platforms: ${{ inputs.platforms }}
        push: true
        tags: |
          sommd/${{ inputs.image }}:${{ inputs.tag }}
          ${{ inputs.latest == 'true' && format('sommd/{0}:latest', inputs.image) || '' }}
