#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -euo pipefail

# copy default config files if they don't exist
if [[ ! -f /config/nginx/dumb-auth-location.conf ]]; then
    cp /defaults/nginx/dumb-auth-location.conf.sample /config/nginx/dumb-auth-location.conf
fi
if [[ ! -f /config/nginx/dumb-auth-server.conf ]]; then
    cp /defaults/nginx/dumb-auth-server.conf.sample /config/nginx/dumb-auth-server.conf
fi

# copy new samples
cp /defaults/nginx/dumb-auth-location.conf.sample /config/nginx/dumb-auth-location.conf.sample
cp /defaults/nginx/dumb-auth-server.conf.sample /config/nginx/dumb-auth-server.conf.sample
