name: Dev build

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          version: 0.0.0-dev+${{ github.sha }}
          target: ${{ matrix.target }}
          test: false

  docker:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
          - dumb-auth
          - dumb-auth-swag-mod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build and push
        uses: ./.github/actions/docker
        with:
          image: ${{ matrix.image }}
          platforms: linux/amd64
          tag: dev-${{ github.sha }}
