name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # MAJOR.MINOR.PATCH
      - "[0-9]+.[0-9]+.[0-9]+-[A-Za-z]+" # MAJOR.MINOR.PATCH-pre
      - "[0-9]+.[0-9]+.[0-9]+-[A-Za-z]+.[0-9]+" # MAJOR.MINOR.PATCH-pre.num

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          version: ${{ github.ref_name }}
          target: ${{ matrix.target }}

  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          pattern: dumb-auth-*
          merge-multiple: true
      - name: Create Github release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --generate-notes \
            ${{ contains(github.ref_name, '-') && '--prerelease' || '' }} \
            --verify-tag \
            '${{ github.ref_name }}' \
            dumb-auth-*

  docker:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
          - dumb-auth
          - dumb-auth-swag-mod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build and push
        uses: ./.github/actions/docker
        with:
          image: ${{ matrix.image }}
          tag: ${{ github.ref_name }}
          latest: ${{ !contains(github.ref_name, '-') }}
