name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+ # vMAJOR.MINOR.PATCH

permissions: write-all

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        target: [x86_64-unknown-linux-gnu]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set version
        run: sed -i '/^\[package\]$/a version = "'"${GITHUB_REF_NAME#v}"'"' Cargo.toml
      - name: Install target toolchain
        run: rustup target add '${{ matrix.target }}'
      - name: Build release
        run: cargo build --target '${{ matrix.target }}' --release
      - name: Test release
        run: cargo test --target '${{ matrix.target }}' --release
      - name: Create Github release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --draft \
            --generate-notes \
            --verify-tag \
            '${{ github.ref_name }}' \
            'target/${{ matrix.target }}/release/dumb-auth#dumb-auth-${{ github.ref_name }}-${{ matrix.target }}'
